logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    br.com.customer.orders: DEBUG

spring:
  main:
    banner-mode: 'off'
  application:
    name: customer-orders-api
  security:
    user:
      name: ${API_USER:admin}
      password: ${API_PASSWORD:admin}
      roles: USER
  hateoas:
    use-hal-as-default-json-media-type: false
  jackson:
    serialization:
      fail-on-empty-beans: false
    xml:
      enabled: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_DB:customer-orders}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:Vr*SJ3<@~2}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default:
    title: ${spring.application.name}
    description: Documentation
    terms-of-service: https://github.com/brow-joe
    license:
      name: private
      url: https://github.com/brow-joe
    version: 1.0.0