version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: coade
    restart: always
    environment:
      - MYSQL_DATABASE=customer-orders
      - MYSQL_ROOT_PASSWORD=Vr*SJ3<@~2
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    network_mode: "host"
volumes:
  mysql-volume:
    driver: local